### ISSUE TITLE
Fehler in https://github.com/HeinrichG-V12/M70_rusEFI

### ISSUE THREAD

**Issue by mi-hol** [HeinrichG-V12/M70_rusEFI#1]
Wenn man im README.md  auf "X69 pinout, male on engine harness side" klickt, kommt ein 404 "not found" Fehler
ist der Link https://github.com/HeinrichG-V12/M70_rusEFI/blob/main/hardware/x69.md richtig?

**Comment by HeinrichG-V12** [comment]
Gefixt, danke für's Bescheidgeben!

**Comment by mi-hol** [comment]
Gerne, wir haben ja gleichartige Interessen und sind fast Nachbarn :)
Leider hab ich auf deiner HomePage keine Möglichkeit gefunden Dich zu kontaktieren

**Comment by HeinrichG-V12** [comment]
Du kannst mich unter heinrich@bmw-rudel.de am einfachsten erreichen.
